[package]
name = "rustot"
version = "0.1.0"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "AWS IoT"
readme = "README.md"
keywords = ["iot", "no-std"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/rustot"
edition = "2018"
documentation = "https://docs.rs/rustot"

[lib]
name = "rustot"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
heapless = { version = "0.5.5", features = ["serde", "ufmt-impl"] }
serde = { version = "^1", default-features = false, features = ["derive"] }
serde_cbor = { version = "^0.11", default-features = false }
bitmaps = { version = "^2", default-features = false }
embedded-hal = "1.0.0-alpha.4"
serde-json-core = "0.2.0"
nb = "^1"
ufmt = "0.1.0"
# mqttrust = "0.1.0"
mqttrust = { git = "https://github.com/BlackbirdHQ/mqttrust", rev = "af6407b" }
typenum = "^1"
defmt = "^0.2"

[dev-dependencies]
native-tls = "^0.2"
rust-crypto = "^0.2"

[features]
default = []

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []