[package]
name = "rustot"
version = "0.0.1"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "AWS IoT"
readme = "README.md"
keywords = ["iot", "no-std"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/rustot"
edition = "2018"
documentation = "https://docs.rs/rustot"

[lib]
name = "rustot"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
embedded-hal = { git = "https://github.com/MathiasKoch/embedded-hal", branch = "feature/alternative-storage" }
nb = "^1"
ufmt = "0.1.0"
heapless = { version = "0.5.5", features = ["serde", "ufmt-impl"] }
mqttrust = { git = "https://github.com/BlackbirdHQ/mqttrust", branch = "enhancement/defmt" }
no-std-net = "0.4.0"
serde = { version = "^1", default-features = false, features = ["derive"] }
serde-json-core = { git = "https://github.com/MathiasKoch/serde-json-core", branch = "factbird_mini" }
serde_cbor =  { version = "^0.11", default-features = false }
bitmaps = { version = "^2", default-features = false }
typenum = "^1"

defmt = { git = "https://github.com/knurling-rs/defmt", branch = "main" }

[dev-dependencies]
embedded-nal = { git = "https://github.com/MathiasKoch/embedded-nal", branch = "factbird-mini-1.0" }
native-tls = "^0.2"
rust-crypto = "^0.2"

[features]
default = []

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
